### ISSUE TITLE
Blog extension not saving 

### ISSUE THREAD

**Issue by juanalbglz** [smiffy6969/razorCMS-extensions#1]
Testing on http://macaronesico.com but the blog extension doesnt seems to work fine.
Anybody else with this problem?
Great software!

**Comment by smiffy6969** [comment]
Have you tried upgrading to latest version or are you on it already? This fixes a bug with dB driver.
Paul
Sent using CloudMagic
On Wed, Dec 10, 2014 at 7:27 pm, J A G notifications@github.com wrote:Testing on http://macaronesico.com but the blog extension doesnt seems to work fine.
Anybody else with this problem?
Great software!

**Comment by juanalbglz** [comment]
Already checked
I was trying to install over softaculous on cpanel, but no suphp :(
thanks

**Comment by smiffy6969** [comment]
Yep that would do it. You either need suphp or you need to give write permissions to every file..... As the system maintains itself it needs to be able to write over any file.
To be honest, if the server is not using suphp I would consider a better host. It is a pretty fundamental module and it is better security wise as you can keep your files permissions tighter without loosing write access.
There are a few alternatives but they would require laying with users and groups.
Ta
Paul
Sent using CloudMagic
On Wed, Dec 10, 2014 at 9:36 pm, J A G notifications@github.com wrote:Already checked
I was trying to install over softaculous on cpanel, but no suphp :(
thanks
